<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<UserSecretsId>44aa9ca0-6d7c-4b63-8157-f15f958a2554</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\API\API.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="FluentAssertions" Version="8.9.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="API.Common" />
		<Using Include="API.Data" />
		<Using Include="API.Services.Abstractions" />
		<Using Include="Shared.Enum" />
		<Using Include="System.Security.Claims" />
		<Using Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>
</Project>