<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<UserSecretsId>44aa9ca0-6d7c-4b63-8157-f15f958a2554</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\src\Server\API\API.Web.csproj" />
		<ProjectReference Include="..\..\..\src\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Moq" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Shared.Enum" />
		<Using Include="System.Security.Claims" />
		<Using Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Application\Features\Message\" />
	  <Folder Include="Application\Features\Chat\" />
	  <Folder Include="Application\Features\Admin\" />
	  <Folder Include="Application\Features\Department\" />
	  <Folder Include="Application\Mapping\" />
	  <Folder Include="Domain\" />
	</ItemGroup>
</Project>