<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- Нет OutputType = это библиотека по умолчанию -->
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
	  <AvaloniaXaml Remove="Assets\Icons.axaml" />
	  <AvaloniaXaml Remove="Assets\Styles\Base\Animations.axaml" />
	  <AvaloniaXaml Remove="Assets\Styles\Base\MainStyle.axaml" />
	  <AvaloniaXaml Remove="Assets\Styles\MessageStyles.axaml" />
	  <AvaloniaXaml Remove="Assets\Styles\Themes\Colored.axaml" />
	  <AvaloniaXaml Remove="Assets\Styles\Themes\DarkTheme.axaml" />
	  <AvaloniaXaml Remove="Assets\Styles\Themes\LightTheme.axaml" />
	</ItemGroup>
	<ItemGroup>
	  <AvaloniaResource Include="Assets\avalonia-logo.ico" />
	  <AvaloniaResource Include="Assets\Fonts\NotoColorEmoji.ttf" />
	  <AvaloniaResource Include="Assets\Icons.axaml" />
	  <AvaloniaResource Include="Assets\Images\default-avatar.webp" />
	  <AvaloniaResource Include="Assets\Images\Logo.png" />
	  <AvaloniaResource Include="Assets\Images\Logo.svg" />
	  <AvaloniaResource Include="Assets\Images\LogoCircle.svg" />
	  <AvaloniaResource Include="Assets\logo-circle.ico" />
	  <AvaloniaResource Include="Assets\Styles\Base\Animations.axaml">
	    <SubType>Designer</SubType>
	  </AvaloniaResource>
	  <AvaloniaResource Include="Assets\Styles\Base\MainStyle.axaml">
	    <SubType>Designer</SubType>
	  </AvaloniaResource>
	  <AvaloniaResource Include="Assets\Styles\MessageStyles.axaml">
	    <SubType>Designer</SubType>
	  </AvaloniaResource>
	  <AvaloniaResource Include="Assets\Styles\Themes\Colored.axaml">
	    <SubType>Designer</SubType>
	  </AvaloniaResource>
	  <AvaloniaResource Include="Assets\Styles\Themes\DarkTheme.axaml">
	    <SubType>Designer</SubType>
	  </AvaloniaResource>
	  <AvaloniaResource Include="Assets\Styles\Themes\LightTheme.axaml">
	    <SubType>Designer</SubType>
	  </AvaloniaResource>
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Assets\logo.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
		<PackageReference Include="sqlite-net-pcl" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Using Include="CommunityToolkit.Mvvm.ComponentModel" />
	  <Using Include="CommunityToolkit.Mvvm.Input" />
	  <Using Include="Core.Infrastructure.Configuration" />
	  <Using Include="Core.Services.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\Images\Avatars\" />
	  <Folder Include="Assets\Images\Icons\" />
	  <Folder Include="Assets\Images\Illustrations\" />
	  <Folder Include="Views\Chat\Poll\" />
	  <Folder Include="Views\Controls\Admin\" />
	</ItemGroup>
</Project>