global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Data.Converters;
global using Avalonia.Media;
global using Avalonia.Threading;
global using Shared.Contracts.Chat;
global using Shared.Contracts.Message;
global using Shared.Contracts.Notification;
global using Shared.Contracts.Poll;
global using Shared.Contracts.ReadReceipt;
global using Shared.Contracts.Search;
global using Shared.Contracts.User;
global using Shared.Enum;
global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using Application = Avalonia.Application;
global using Button = Avalonia.Controls.Button;