// <auto-generated />
using System;
using MessengerAPI.Model;
using MessengerShared.Enum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessengerAPI.Migrations
{
    [DbContext(typeof(MessengerDbContext))]
    partial class MessengerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chat_role", new[] { "member", "admin", "owner" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chat_type", new[] { "Chat", "Department", "Contact", "department_heads" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "system_event_type", new[] { "chat_created", "member_added", "member_left", "member_removed", "role_changed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "system_event_type", "system_event_type", new[] { "chat_created", "member_added", "member_removed", "member_left", "role_changed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "theme", new[] { "dark", "light", "system" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "theme", "theme", new[] { "light", "dark", "system" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessengerAPI.Model.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"Chats_Id_seq\"'::regclass)");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("LastMessageTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_message_time");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<ChatType>("Type")
                        .HasColumnType("chat_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("chats_pkey");

                    b.HasIndex("CreatedById");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.ChatMember", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_read_at");

                    b.Property<int?>("LastReadMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("last_read_message_id");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<ChatRole>("Role").HasColumnType("chat_role").HasColumnName("role");

                    b.HasKey("ChatId", "UserId").HasName("chat_members_pkey");

                    b.HasIndex(new[] { "ChatId", "UserId" }, "UQ_Chat_User").IsUnique();

                    b.HasIndex(new[] { "LastReadMessageId" }, "idx_chat_members_last_read_message_id");

                    b.HasIndex(new[] { "UserId" }, "idx_chat_members_user_id");

                    b.ToTable("chat_members", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"Departments_Id_seq\"'::regclass)");

                    b.Property<int?>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<int?>("HeadId")
                        .HasColumnType("integer")
                        .HasColumnName("head_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_department_id");

                    b.HasKey("Id")
                        .HasName("departments_pkey");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex(new[] { "ChatId" }, "Departments_ChatId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "HeadId" }, "idx_departments_head_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"Messages_Id_seq\"'::regclass)");

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("edited_at");

                    b.Property<int?>("ForwardedFromMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("forwarded_from_message_id");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_message");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("reply_to_message_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<SystemEventType?>("SystemEventType")
                        .HasColumnType("system_event_type")
                        .HasColumnName("system_event_type");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("messages_pkey");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ChatId", "CreatedAt" }, "idx_messages_chatid_createdat");

                    b.HasIndex(new[] { "ForwardedFromMessageId" }, "idx_messages_forwarded_from_message_id");

                    b.HasIndex(new[] { "ReplyToMessageId" }, "idx_messages_reply_to_message_id");

                    b.HasIndex(new[] { "TargetUserId" }, "idx_messages_target_user_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.MessageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"MessageFiles_id_seq\"'::regclass)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("message_files_pkey");

                    b.HasIndex("MessageId");

                    b.ToTable("message_files", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"Polls_Id_seq\"'::regclass)");

                    b.Property<bool?>("AllowsMultipleAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allows_multiple_answers");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closes_at");

                    b.Property<bool?>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_anonymous");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.HasKey("Id")
                        .HasName("polls_pkey");

                    b.HasIndex(new[] { "MessageId" }, "idx_polls_message_id");

                    b.ToTable("polls", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"PollOptions_Id_seq\"'::regclass)");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("option_text");

                    b.Property<int>("PollId")
                        .HasColumnType("integer")
                        .HasColumnName("poll_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("poll_options_pkey");

                    b.HasIndex("PollId");

                    b.ToTable("poll_options", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.PollVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"PollVotes_Id_seq\"'::regclass)");

                    b.Property<int>("OptionId")
                        .HasColumnType("integer")
                        .HasColumnName("option_id");

                    b.Property<int>("PollId")
                        .HasColumnType("integer")
                        .HasColumnName("poll_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("voted_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("poll_votes_pkey");

                    b.HasIndex("OptionId");

                    b.HasIndex(new[] { "PollId", "UserId", "OptionId" }, "UQ_Poll_User_Option_Vote")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "idx_poll_votes_user_id");

                    b.ToTable("poll_votes", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"RefreshTokens_Id_seq\"'::regclass)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("family_id");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jwt_id");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("integer")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_refresh_tokens_expires_at");

                    b.HasIndex(new[] { "FamilyId" }, "idx_refresh_tokens_family_id");

                    b.HasIndex(new[] { "TokenHash" }, "idx_refresh_tokens_token_hash");

                    b.HasIndex(new[] { "UserId" }, "idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("system_settings_pkey");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"Users_Id_seq\"'::regclass)");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("Midname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("midname");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "DepartmentId" }, "idx_users_department_id");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.UserSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<Theme?>("Theme")
                        .HasColumnType("theme")
                        .HasColumnName("theme");

                    b.HasKey("UserId")
                        .HasName("user_settings_pkey");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.VoiceMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("audio/wav")
                        .HasColumnName("content_type");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.HasKey("MessageId")
                        .HasName("voice_messages_pkey");

                    b.ToTable("voice_messages", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Model.Chat", b =>
                {
                    b.HasOne("MessengerAPI.Model.User", "CreatedBy")
                        .WithMany("Chats")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Chats_CreatedById_fkey");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MessengerAPI.Model.ChatMember", b =>
                {
                    b.HasOne("MessengerAPI.Model.Chat", "Chat")
                        .WithMany("ChatMembers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ChatMembers_ChatId_fkey");

                    b.HasOne("MessengerAPI.Model.Message", "LastReadMessage")
                        .WithMany("ChatMembers")
                        .HasForeignKey("LastReadMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("ChatMembers_LastReadMessageId_fkey");

                    b.HasOne("MessengerAPI.Model.User", "User")
                        .WithMany("ChatMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ChatMembers_UserId_fkey");

                    b.Navigation("Chat");

                    b.Navigation("LastReadMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerAPI.Model.Department", b =>
                {
                    b.HasOne("MessengerAPI.Model.Chat", "Chat")
                        .WithOne("Department")
                        .HasForeignKey("MessengerAPI.Model.Department", "ChatId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Departments_ChatId_fkey");

                    b.HasOne("MessengerAPI.Model.User", "Head")
                        .WithMany("Departments")
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Departments_Head_fkey");

                    b.HasOne("MessengerAPI.Model.Department", "ParentDepartment")
                        .WithMany("InverseParentDepartment")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Departments_Parent_fkey");

                    b.Navigation("Chat");

                    b.Navigation("Head");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("MessengerAPI.Model.Message", b =>
                {
                    b.HasOne("MessengerAPI.Model.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Messages_ChatId_fkey");

                    b.HasOne("MessengerAPI.Model.Message", "ForwardedFromMessage")
                        .WithMany("InverseForwardedFromMessage")
                        .HasForeignKey("ForwardedFromMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_ForwardedFromMessageId_fkey");

                    b.HasOne("MessengerAPI.Model.Message", "ReplyToMessage")
                        .WithMany("InverseReplyToMessage")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_ReplyToMessageId_fkey");

                    b.HasOne("MessengerAPI.Model.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Messages_SenderId_fkey");

                    b.HasOne("MessengerAPI.Model.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_TargetUserId_fkey");

                    b.Navigation("Chat");

                    b.Navigation("ForwardedFromMessage");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("MessengerAPI.Model.MessageFile", b =>
                {
                    b.HasOne("MessengerAPI.Model.Message", "Message")
                        .WithMany("MessageFiles")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MessageFiles_MessageId_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessengerAPI.Model.Poll", b =>
                {
                    b.HasOne("MessengerAPI.Model.Message", "Message")
                        .WithMany("Polls")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Polls_MessageId_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessengerAPI.Model.PollOption", b =>
                {
                    b.HasOne("MessengerAPI.Model.Poll", "Poll")
                        .WithMany("PollOptions")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollOptions_PollId_fkey");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("MessengerAPI.Model.PollVote", b =>
                {
                    b.HasOne("MessengerAPI.Model.PollOption", "Option")
                        .WithMany("PollVotes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollVotes_OptionId_fkey");

                    b.HasOne("MessengerAPI.Model.Poll", "Poll")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollVotes_PollId_fkey");

                    b.HasOne("MessengerAPI.Model.User", "User")
                        .WithMany("PollVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollVotes_UserId_fkey");

                    b.Navigation("Option");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerAPI.Model.RefreshToken", b =>
                {
                    b.HasOne("MessengerAPI.Model.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("RefreshTokens_ReplacedBy_fkey");

                    b.HasOne("MessengerAPI.Model.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("RefreshTokens_UserId_fkey");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerAPI.Model.User", b =>
                {
                    b.HasOne("MessengerAPI.Model.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Users_DepartmentId_fkey");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MessengerAPI.Model.UserSetting", b =>
                {
                    b.HasOne("MessengerAPI.Model.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("MessengerAPI.Model.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserSettings_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerAPI.Model.VoiceMessage", b =>
                {
                    b.HasOne("MessengerAPI.Model.Message", "Message")
                        .WithOne("VoiceMessage")
                        .HasForeignKey("MessengerAPI.Model.VoiceMessage", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("VoiceMessages_MessageId_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessengerAPI.Model.Chat", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("Department");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MessengerAPI.Model.Department", b =>
                {
                    b.Navigation("InverseParentDepartment");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MessengerAPI.Model.Message", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("InverseForwardedFromMessage");

                    b.Navigation("InverseReplyToMessage");

                    b.Navigation("MessageFiles");

                    b.Navigation("Polls");

                    b.Navigation("VoiceMessage");
                });

            modelBuilder.Entity("MessengerAPI.Model.Poll", b =>
                {
                    b.Navigation("PollOptions");

                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("MessengerAPI.Model.PollOption", b =>
                {
                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("MessengerAPI.Model.User", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("Chats");

                    b.Navigation("Departments");

                    b.Navigation("Messages");

                    b.Navigation("PollVotes");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
