FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base

WORKDIR /app

RUN apt-get update && apt-get install -y libkrb5-3

EXPOSE 5274
EXPOSE 5275/udp

RUN mkdir -p /app/wwwroot/uploads /app/wwwroot/avatars

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY ["src/Server/API/API.Web.csproj", "src/Server/API/"]
COPY ["src/Server/API.Domain/API.Domain.csproj", "src/Server/API.Domain/"]
COPY ["src/Server/API.Application/API.Application.csproj", "src/Server/API.Application/"]
COPY ["src/Server/API.Infrastructure/API.Infrastructure.csproj", "src/Server/API.Infrastructure/"]
COPY ["src/Shared/Shared.csproj", "src/Shared/"]

RUN dotnet restore "src/Server/API/API.Web.csproj"

COPY . .

RUN mkdir -p /src/src/Server/API.Infrastructure/Database/SeedData

COPY src/Server/API.Infrastructure/Database/SeedData/*.json /src/src/Server/API.Infrastructure/Database/SeedData/

RUN dotnet publish "src/Server/API/API.Web.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore

FROM base AS final

WORKDIR /app

COPY --from=build /app/publish .

RUN mkdir -p /app/Data/SeedData

COPY --from=build /src/src/Server/API.Infrastructure/Database/SeedData/*.json /app/Data/SeedData/

ENTRYPOINT ["dotnet", "API.Web.dll"]