// <auto-generated />
using System;
using API.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shared.Enum;

#nullable disable

namespace API.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MessengerDbContext))]
    [Migration("20260623123656_FixPollNullableBool")]
    partial class FixPollNullableBool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chat_role", new[] { "member", "admin", "owner" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chat_type", new[] { "chat", "department", "contact", "department_heads" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "system_event_type", new[] { "chat_created", "member_added", "member_removed", "member_left", "role_changed", "call_started", "call_ended", "message_pinned", "message_unpinned", "chat_avatar_updated" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "theme", new[] { "light", "dark", "system", "colored" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status_type", new[] { "online", "away", "busy", "do_not_disturb" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("LastMessageTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_message_time");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("ShowHistoryForNewMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_history_for_new_members");

                    b.Property<ChatType>("Type")
                        .HasColumnType("chat_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("chats_pkey");

                    b.HasIndex("CreatedById");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.ChatMember", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_read_at");

                    b.Property<int?>("LastReadMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("last_read_message_id");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<ChatRole>("Role")
                        .HasColumnType("chat_role")
                        .HasColumnName("role");

                    b.HasKey("ChatId", "UserId")
                        .HasName("chat_members_pkey");

                    b.HasIndex(new[] { "LastReadMessageId" }, "idx_chat_members_last_read_message_id");

                    b.HasIndex(new[] { "UserId" }, "idx_chat_members_user_id");

                    b.ToTable("chat_members", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<int?>("HeadId")
                        .HasColumnType("integer")
                        .HasColumnName("head_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_department_id");

                    b.HasKey("Id")
                        .HasName("departments_pkey");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex(new[] { "ChatId" }, "Departments_ChatId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "HeadId" }, "idx_departments_head_id")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pinned_at");

                    b.Property<int?>("PinnedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("pinned_by_user_id");

                    b.Property<bool>("message_type")
                        .HasColumnType("boolean")
                        .HasColumnName("message_type");

                    b.HasKey("Id")
                        .HasName("messages_pkey");

                    b.HasIndex("PinnedByUserId");

                    b.HasIndex(new[] { "ChatId", "CreatedAt" }, "idx_messages_chatid_createdat");

                    b.HasIndex(new[] { "ChatId", "PinnedAt" }, "idx_messages_chatid_pinnedat")
                        .HasFilter("pinned_at IS NOT NULL");

                    b.ToTable("messages", (string)null);

                    b.HasDiscriminator<bool>("message_type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("API.Domain.Entities.MessageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("message_files_pkey");

                    b.HasIndex("MessageId");

                    b.ToTable("message_files", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsMultipleAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allows_multiple_answers");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closes_at");

                    b.Property<bool>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_anonymous");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.HasKey("Id")
                        .HasName("polls_pkey");

                    b.HasIndex(new[] { "MessageId" }, "idx_polls_message_id")
                        .IsUnique();

                    b.ToTable("polls", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("option_text");

                    b.Property<int>("PollId")
                        .HasColumnType("integer")
                        .HasColumnName("poll_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("poll_options_pkey");

                    b.HasIndex("PollId");

                    b.ToTable("poll_options", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.PollVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OptionId")
                        .HasColumnType("integer")
                        .HasColumnName("option_id");

                    b.Property<int>("PollId")
                        .HasColumnType("integer")
                        .HasColumnName("poll_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("voted_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("poll_votes_pkey");

                    b.HasIndex("OptionId");

                    b.HasIndex(new[] { "PollId", "UserId", "OptionId" }, "UQ_Poll_User_Option_Vote")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "idx_poll_votes_user_id");

                    b.ToTable("poll_votes", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("family_id");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jwt_id");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("integer")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_refresh_tokens_expires_at");

                    b.HasIndex(new[] { "FamilyId" }, "idx_refresh_tokens_family_id");

                    b.HasIndex(new[] { "ReplacedByTokenId" }, "idx_refresh_tokens_replaced_by");

                    b.HasIndex(new[] { "TokenHash" }, "idx_refresh_tokens_token_hash");

                    b.HasIndex(new[] { "UserId" }, "idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("system_settings_pkey");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("Midname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("midname");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StatusExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("status_expires_at");

                    b.Property<UserStatusType>("StatusType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("user_status_type")
                        .HasDefaultValue(UserStatusType.Online)
                        .HasColumnName("status_type");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "DepartmentId" }, "idx_users_department_id");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.UserSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<Theme?>("Theme")
                        .HasColumnType("theme")
                        .HasColumnName("theme");

                    b.HasKey("UserId")
                        .HasName("user_settings_pkey");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.VoiceMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Waveform")
                        .HasColumnType("text")
                        .HasColumnName("waveform");

                    b.HasKey("MessageId")
                        .HasName("voice_messages_pkey");

                    b.ToTable("voice_messages", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.SystemMessage", b =>
                {
                    b.HasBaseType("API.Domain.Entities.Message");

                    b.Property<string>("Content")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("InitiatorId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<SystemEventType>("SystemEventType")
                        .HasColumnType("system_event_type")
                        .HasColumnName("system_event_type");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex(new[] { "TargetUserId" }, "idx_messages_target_user_id");

                    b.HasDiscriminator().HasValue(true);
                });

            modelBuilder.Entity("API.Domain.Entities.UserMessage", b =>
                {
                    b.HasBaseType("API.Domain.Entities.Message");

                    b.Property<string>("Content")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("edited_at");

                    b.Property<int?>("ForwardedFromMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("forwarded_from_message_id");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("reply_to_message_id");

                    b.Property<int?>("SenderId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ForwardedFromMessageId" }, "idx_messages_forwarded_from_message_id");

                    b.HasIndex(new[] { "ReplyToMessageId" }, "idx_messages_reply_to_message_id");

                    b.HasDiscriminator().HasValue(false);
                });

            modelBuilder.Entity("API.Domain.Entities.Chat", b =>
                {
                    b.HasOne("API.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedChats")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Chats_CreatedById_fkey");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("API.Domain.Entities.ChatMember", b =>
                {
                    b.HasOne("API.Domain.Entities.Chat", "Chat")
                        .WithMany("ChatMembers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ChatMembers_ChatId_fkey");

                    b.HasOne("API.Domain.Entities.Message", "LastReadMessage")
                        .WithMany("ChatMembers")
                        .HasForeignKey("LastReadMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("ChatMembers_LastReadMessageId_fkey");

                    b.HasOne("API.Domain.Entities.User", "User")
                        .WithMany("ChatMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ChatMembers_UserId_fkey");

                    b.Navigation("Chat");

                    b.Navigation("LastReadMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Domain.Entities.Department", b =>
                {
                    b.HasOne("API.Domain.Entities.Chat", "Chat")
                        .WithOne("Department")
                        .HasForeignKey("API.Domain.Entities.Department", "ChatId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Departments_ChatId_fkey");

                    b.HasOne("API.Domain.Entities.User", "Head")
                        .WithMany("HeadedDepartments")
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Departments_Head_fkey");

                    b.HasOne("API.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("InverseParentDepartment")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Departments_Parent_fkey");

                    b.Navigation("Chat");

                    b.Navigation("Head");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("API.Domain.Entities.Message", b =>
                {
                    b.HasOne("API.Domain.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Messages_ChatId_fkey");

                    b.HasOne("API.Domain.Entities.User", "PinnedByUser")
                        .WithMany()
                        .HasForeignKey("PinnedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_PinnedByUserId_fkey");

                    b.Navigation("Chat");

                    b.Navigation("PinnedByUser");
                });

            modelBuilder.Entity("API.Domain.Entities.MessageFile", b =>
                {
                    b.HasOne("API.Domain.Entities.UserMessage", "Message")
                        .WithMany("MessageFiles")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MessageFiles_MessageId_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("API.Domain.Entities.Poll", b =>
                {
                    b.HasOne("API.Domain.Entities.UserMessage", "Message")
                        .WithOne("Poll")
                        .HasForeignKey("API.Domain.Entities.Poll", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Polls_MessageId_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("API.Domain.Entities.PollOption", b =>
                {
                    b.HasOne("API.Domain.Entities.Poll", "Poll")
                        .WithMany("PollOptions")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollOptions_PollId_fkey");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("API.Domain.Entities.PollVote", b =>
                {
                    b.HasOne("API.Domain.Entities.PollOption", "Option")
                        .WithMany("PollVotes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollVotes_OptionId_fkey");

                    b.HasOne("API.Domain.Entities.Poll", "Poll")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollVotes_PollId_fkey");

                    b.HasOne("API.Domain.Entities.User", "User")
                        .WithMany("PollVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PollVotes_UserId_fkey");

                    b.Navigation("Option");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("API.Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("RefreshTokens_ReplacedBy_fkey");

                    b.HasOne("API.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("RefreshTokens_UserId_fkey");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Domain.Entities.User", b =>
                {
                    b.HasOne("API.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Users_DepartmentId_fkey");

                    b.OwnsOne("API.Domain.Entities.UserPassword", "Password", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Department");

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.UserSetting", b =>
                {
                    b.HasOne("API.Domain.Entities.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("API.Domain.Entities.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserSettings_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Domain.Entities.VoiceMessage", b =>
                {
                    b.HasOne("API.Domain.Entities.UserMessage", "Message")
                        .WithOne("VoiceMessage")
                        .HasForeignKey("API.Domain.Entities.VoiceMessage", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("VoiceMessages_MessageId_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("API.Domain.Entities.SystemMessage", b =>
                {
                    b.HasOne("API.Domain.Entities.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_SenderId_fkey");

                    b.HasOne("API.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_TargetUserId_fkey");

                    b.Navigation("Initiator");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("API.Domain.Entities.UserMessage", b =>
                {
                    b.HasOne("API.Domain.Entities.UserMessage", "ForwardedFromMessage")
                        .WithMany("InverseForwardedFromMessage")
                        .HasForeignKey("ForwardedFromMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_ForwardedFromMessageId_fkey");

                    b.HasOne("API.Domain.Entities.UserMessage", "ReplyToMessage")
                        .WithMany("InverseReplyToMessage")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_ReplyToMessageId_fkey");

                    b.HasOne("API.Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Messages_SenderId_fkey");

                    b.Navigation("ForwardedFromMessage");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("API.Domain.Entities.Chat", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("Department");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("API.Domain.Entities.Department", b =>
                {
                    b.Navigation("InverseParentDepartment");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("API.Domain.Entities.Message", b =>
                {
                    b.Navigation("ChatMembers");
                });

            modelBuilder.Entity("API.Domain.Entities.Poll", b =>
                {
                    b.Navigation("PollOptions");

                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("API.Domain.Entities.PollOption", b =>
                {
                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("API.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("CreatedChats");

                    b.Navigation("HeadedDepartments");

                    b.Navigation("PollVotes");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentMessages");

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("API.Domain.Entities.UserMessage", b =>
                {
                    b.Navigation("InverseForwardedFromMessage");

                    b.Navigation("InverseReplyToMessage");

                    b.Navigation("MessageFiles");

                    b.Navigation("Poll");

                    b.Navigation("VoiceMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
