<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<EnableDefaultContentItems>true</EnableDefaultContentItems>
		<OutputType>WinExe</OutputType>

		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
		<UseRidGraph>true</UseRidGraph>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<ApplicationIcon>Assets\logo.ico</ApplicationIcon>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<AssemblyName>ВнутрьСеть</AssemblyName>
		<AssemblyTitle></AssemblyTitle>
		<ImplicitUsings>enable</ImplicitUsings>

		<PlatformTarget>x64</PlatformTarget>

		<GenerateDocumentationFile>False</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.X11" />
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Markup.Declarative" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Scrutor" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
		<PackageReference Include="sqlite-net-pcl" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
		<PackageReference Include="Silk.NET.OpenAL" />
		<PackageReference Include="Silk.NET.OpenAL.Extensions.Creative" />
		<PackageReference Include="Silk.NET.OpenAL.Soft.Native" />
		<PackageReference Include="SIPSorcery" />
		<PackageReference Include="Tmds.DBus.Protocol" />
		<PackageReference Include="Concentus" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Remove="Assets\Animations\**" />
		<AvaloniaXaml Remove="Assets\Animations\**" />
		<AvaloniaXaml Remove="Models\**" />
		<Compile Remove="Assets\Animations\**" />
		<Compile Remove="Models\**" />
		<EmbeddedResource Remove="Assets\Animations\**" />
		<EmbeddedResource Remove="Models\**" />
		<None Remove="Assets\Animations\**" />
		<None Remove="Models\**" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaXaml Remove="Assets\Animations.axaml" />
		<AvaloniaXaml Remove="Assets\LightTheme.axaml" />
		<AvaloniaXaml Remove="Assets\MainStyle.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\ChatInfoSkeleton.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\ChatListSkeleton.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\ChatMessagesSkeleton.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\Controls.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\MessageStyles.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\Themes\Colored.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\Themes\DarkTheme.axaml" />
		<AvaloniaXaml Remove="Assets\Styles\Themes\LightTheme.axaml" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Assets\Styles\ChatInfoSkeleton.axaml.cs" />
		<Compile Remove="Assets\Styles\ChatListSkeleton.axaml.cs" />
		<Compile Remove="Assets\Styles\ChatMessagesSkeleton.axaml.cs" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\logo.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\Core.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Update="Assets\Styles\Base\MainStyle.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
		<AvaloniaResource Update="Assets\Styles\Base\Animations.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
		<AvaloniaResource Update="Assets\Styles\MessageStyles.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
		<AvaloniaResource Update="Assets\Styles\Themes\Colored.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
		<AvaloniaResource Update="Assets\Styles\Themes\DarkTheme.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
		<AvaloniaResource Update="Assets\Styles\Themes\LightTheme.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Assets\Images\Icons\" />
		<Folder Include="Assets\Images\Avatars\" />
		<Folder Include="Assets\Images\Illustrations\" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.Wsl.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.Local.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
		<BaseOutputPath>/tmp/MessengerDesktop/bin/</BaseOutputPath>
		<BaseIntermediateOutputPath>/tmp/MessengerDesktop/obj/</BaseIntermediateOutputPath>
	</PropertyGroup>

	<Target Name="CopyToWindowsOutput" AfterTargets="Publish" Condition="'$(RuntimeIdentifier)' == 'win-x64'">
		<RemoveDir Directories="$(SolutionDir)Publish\Windows\" />
		<Copy SourceFiles="@(PublishedFiles)" DestinationFolder="$(SolutionDir)Publish\Windows\%(RecursiveDir)" />
		<Message Importance="high" Text="Published for Windows to $(SolutionDir)Publish\Windows" />
	</Target>

	<Target Name="CopyToLinuxOutput" AfterTargets="Publish" Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
		<RemoveDir Directories="$(SolutionDir)Publish\Linux\" />
		<Copy SourceFiles="@(PublishedFiles)" DestinationFolder="$(SolutionDir)Publish\Linux\%(RecursiveDir)" />
		<Message Importance="high" Text="Published for Linux to $(SolutionDir)Publish\Linux" />
	</Target>
</Project>